version: '3.3'
services:
  server:
    image: stupefy-soap-service:latest
    volumes:
      - ./src:/home/app/src
      - ./pom.xml:/home/app/pom.xml
    ports:
      - 3101:8080
    networks:
      - stupefy-network
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3309:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - stupefy-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db:
    driver: local

networks:
  stupefy-network:
    driver: bridge
