version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - ADMIN_USER=${WILDFLY_ADMIN}
      - ADMIN_PASSWORD=${WILDFLY_ADMIN_PASSWORD}
    volumes:
      - ./target/stupefy-subscription.war:/opt/jboss/wildfly/standalone/deployments/stupefy-subscription.war
      - ./scripts:/opt/jboss/scripts
    ports:
      - 3101:8080
      - 9990:9990
    networks:
      - stupefy-network
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - 3309:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - stupefy-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  db:
    driver: local

networks:
  stupefy-network:
    driver: bridge
